# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: ac552329@gamil.com
author_name: Aditya Chatterjee
preset_name: starter
project_name: DurgaDao-frontend

